// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOg6V_Ruye_tqVGHtREz_cqrcy7Ma66so',
    appId: '1:317848150863:web:c9ef4007bf0da3bd6adb3a',
    messagingSenderId: '317848150863',
    projectId: 'hotel-manas-system',
    authDomain: 'hotel-manas-system.firebaseapp.com',
    storageBucket: 'hotel-manas-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABTmGVaXlVYm-ZlwX_4AfCxAQbrXfyhNE',
    appId: '1:317848150863:android:118249db9bbfc3896adb3a',
    messagingSenderId: '317848150863',
    projectId: 'hotel-manas-system',
    storageBucket: 'hotel-manas-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt6UIIQV5Z13bdI9KACRjS68JUQlDEHhs',
    appId: '1:317848150863:ios:013e0b7520b771856adb3a',
    messagingSenderId: '317848150863',
    projectId: 'hotel-manas-system',
    storageBucket: 'hotel-manas-system.firebasestorage.app',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOg6V_Ruye_tqVGHtREz_cqrcy7Ma66so',
    appId: '1:317848150863:web:befcadadb5bcd8866adb3a',
    messagingSenderId: '317848150863',
    projectId: 'hotel-manas-system',
    authDomain: 'hotel-manas-system.firebaseapp.com',
    storageBucket: 'hotel-manas-system.firebasestorage.app',
  );
}
